import { configureStore} from "@reduxjs/toolkit";
import actionSliceReducer from "./Redux-action"; // Import the reducer generated by the action slice

// Create the Redux store with the main reducer
export const store = configureStore({
  reducer: {
    action: actionSliceReducer, // Assign the actionSliceReducer to the "actions" substate
  }
})

// Define the RootState type to infer and type the global state
export type RootState = ReturnType<typeof store.getState>;

// Define the AppDispatch type to type the available actions in the application
export type AppDispatch = typeof store.dispatch;
