export const SkillData: Skill_data[] = [
  {
    skill_name: "Html",
    Image: "/Tech/html.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Css",
    Image: "/Tech/css.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/Tech/js.png",
    width: 65,
    height: 65,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/Tech/tailwind.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "React",
    Image: "/Tech/react.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Redux",
    Image: "/Tech/redux.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "React Query",
    Image: "/Tech/reactquery.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/Tech/ts.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/Tech/next.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Json Web Token",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/Tech/framer.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Node js",
    Image: "/Tech/node-js.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Express js",
    Image: "/Tech/express.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/Tech/mongodb.png",
    width: 40,
    height: 40,
  },
  {
    skill_name: "Fire base",
    Image: "/Tech/Firebase.png",
    width: 55,
    height: 55,
  },
  {
    skill_name: "My SQL",
    Image: "/Tech/mysql.png",
    width: 70,
    height: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/Tech/graphql.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "React Native",
    Image: "/Tech/reactnative.png",
    width: 70,
    height: 70,
  },
  {
    skill_name: "Docker",
    Image: "/Tech/docker.webp",
    width: 70,
    height: 70,
  },
  {
    skill_name: "Figma",
    Image: "/Tech/figma.png",
    width: 50,
    height: 50,
  },
  {
    skill_name: "Web Scoket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    height: 70,
  },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    height: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    height: 70,
  },
];

export const Project: Project_data[] = [
  // Web Development Portfolio
  {
    title: "Web Development Portfolio",
    project_id: "0",
    technology_feature: [
      "Tailwind",
      "React",
      "Framer Motion",
      "Three",
      "Javascript",
      "Vite",
    ],
    description:
      "Welcome to my ThreeJS 3D Developer Portfolio project! This repository showcases how I've builded this impressive 3D website using the powerful combination of ThreeJS, React Three Fiber, TailwindCSS, and Framer Motion.",
    package: [
      "@emailjs/browser",
      "@headlessui/react",
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@tailwindcss/aspect-ratio",
      "framer-motion",
      "maath",
      "react",
      "react-dom",
      "react-router-dom",
      "react-tilt",
      "react-vertical-timeline-component",
      "three",
      "tailwindcss",
      "vite",
    ],
    githhub_link: "https://github.com/JjuliSanz/Portfolio",
    frontend: "https://my-portfoli-website.netlify.app/",
    backend: "",
    project_image: "/Projects/portfolio.png",
    Type: "Next js 13",
  },
  // Decentralized Crowdfunding
  {
    title: "Decentralized Crowdfunding App",
    project_id: "1",
    technology_feature: [
      "Solidity",
      "Javascript",
      "Express",
      "Ethers",
      "Next",
      "MongoDB",
      "Css",
    ],
    description:
      "The crowdfunding web3 full-stack app is a decentralized fundraising platform that leverages blockchain technology to revolutionize the way projects and initiatives are funded. It allows individuals and organizations to create campaigns and raise funds from a global network of contributors, all while ensuring transparency, security, and immutability of transactions.",
    package: [
      "@next/font",
      "@thirdweb-dev/react",
      "@thirdweb-dev/sdk",
      "axios",
      "bcryptjs",
      "cors",
      "dotenv",
      "ethers",
      "express",
      "file-saver",
      "jsonwebtoken",
      "mongoose",
      "next",
      "nodemon",
    ],

    githhub_link: "https://github.com/JjuliSanz/Crowdfunding-Dapp",
    frontend: "https://crowdfunding-dapp-web3.vercel.app/",
    backend: "",
    project_image: "/Projects/crowdfunding.png",
    Type: "Next js 13",
  },
  // NFT Card Game
  {
    title: "NFT Card Game",
    project_id: "2",
    technology_feature: [
      "Tailwind",
      "React",
      "Vite",
      "Solidity",
      "Hardhat",
      "Javascript",
      "Ethers",
    ],
    description:
      "This is an NFT Card Game project deployed on the Avalanche Fuji Testnet. The game allows players to engage in 1v1 battles using unique NFT cards. Built with core wallet integration, players can collect, trade, and battle with their NFT cards on the blockchain. The project aims to provide an immersive gaming experience while leveraging the benefits of blockchain technology, ensuring transparency and ownership of the in-game assets.",
    package: [
      "react",
      "react-dom",
      "ethers",
      "react-modal",
      "react-parallax-tilt",
      "react-router-dom",
      "react-tooltip",
      "web3modal",
      "vite",
      "tailwindcss",
    ],
    githhub_link: "https://github.com/JjuliSanz/NFT-Cardgame",
    frontend: "https://etherclash.netlify.app/",
    backend: "",
    project_image: "/Projects/NFTCardgame.png",
    Type: "Next js 13",
  },
  // Web3 Exchange
  {
    title: "Cryptocurrency Sending Application",
    project_id: "3",
    technology_feature: [
      "Solidity",
      "React",
      "Javascript",
      "Ethers",
      "Hardhat",
      "Tailwind",
      "Vite",
    ],
    description:
      "The project is focused on creating a comprehensive Web 3.0 application that enables users to send transactions using blockchain technology. The application aims to provide a seamless and secure platform for users to initiate and process transactions on the blockchain. The project aims to leverage blockchain technology for transactional purposes, ensuring transparency and decentralization in transactions.",
    package: [
      "@tailwindcss/forms",
      "autoprefixer",
      "eth-revert-reason",
      "ethers",
      "framer-motion",
      "postcss",
      "react",
      "react-dom",
      "react-icons",
      "vite",
    ],
    githhub_link: "https://github.com/JjuliSanz/KryptExchange",
    frontend: "https://kryptexchangex.netlify.app/",
    backend: "",
    project_image: "/Projects/kryptexchange.png",
    Type: "Next js 13",
  },
  // Decentralized Domains
  {
    title: "Decentralized domains app",
    project_id: "4",
    technology_feature: [
      "Solidity",
      "Javascript",
      "React",
      "Hardhat",
      "Ethers",
      "Css",
    ],
    description:
      "A decentralized clone of GoDaddy is a platform built on blockchain technology that allows users to buy domain names in a decentralized manner. By decentralizing the domain registration and management process, this clone provides an alternative to traditional domain registrars, offering increased security, privacy, and ownership rights for domain owners. It empowers individuals to truly own and control their online presence, while also contributing to the overall decentralization and resilience of the internet.",
    package: [
      "@openzeppelin/contracts",
      "@testing-library/jest-dom",
      "@testing-library/react",
      "@testing-library/user-event",
      "dotenv",
      "react",
      "react-dom",
      "react-scripts",
      "web-vitals",
    ],
    githhub_link: "https://github.com/JjuliSanz/Dapp-Domain",
    frontend: "https://noisy-disk-5752.on.fleek.co/",
    backend: "",
    project_image: "/Projects/domainapp.png",
    Type: "Next js 13",
  },
  // Nft Marketplace
  {
    title: "Nft Marketplace",
    project_id: "5",
    technology_feature: [
      "Solidity",
      "Ethers",
      "Css",
      "Next",
      "Javascript",
      "Hardhat",
    ],
    description:
      "The NFT Marketplace project is a cutting-edge platform that allows users to buy, sell, and trade unique digital assets known as Non-Fungible Tokens (NFTs). Whether you're an artist looking to showcase your work, a collector seeking rare and valuable NFTs, or an investor interested in this emerging digital asset class, the NFT Marketplace provides a dynamic and vibrant ecosystem to participate in the world of non-fungible tokens.",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@reduxjs/toolkit",
      "framer-motion",
      "maath",
      "react-redux",
    ],
    githhub_link: "https://github.com/JjuliSanz/NFT-Marketplace",
    frontend: "https://juli-nft-marketplace.netlify.app/",
    backend: "",
    project_image: "/Projects/NftMarket.png",
    Type: "Next js 13",
  },
  // Decentralized e-commerce
  {
    title: "Decentralized e-commerce",
    project_id: "6",
    technology_feature: [
      "Solidity",
      "React",
      "Hardhat",
      "Css",
      "Javascript",
      "Ethers",
    ],
    description:
      "The E-commerce dApp is a decentralized application (dApp) that revolutionizes the online shopping experience by leveraging blockchain technology. It provides users with a secure and transparent platform where they can buy products using cryptocurrencies. With this dApp, users can explore a wide range of products from various sellers, ensuring a diverse marketplace. Each product listing includes detailed information, images, and reviews from previous buyers, empowering users to make informed purchasing decisions.",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@reduxjs/toolkit",
      "framer-motion",
      "maath",
      "react-redux",
    ],
    githhub_link: "https://github.com/JjuliSanz/Dapp-e-commerce",
    frontend: "https://gentle-moon-4719.on.fleek.co/",
    backend: "",
    project_image: "/Projects/ecommerceapp.png",
    Type: "Next js 13",
  },
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
];
